# Site Settings
name: JtxBlog
title: 江天祥的博客
description: 永远相信美好的事情即将发生
tags:
  - 博客创建
  - JtxBlog
  - Java教程
  - python教程
  - 前端教程
  - Jtx的博客
  - 米粉的博客
email: tianxiang1314520@gmail.com
# disqus_username: disqus_username
show_hero: true


# Social Media Settings
# Remove the item if you don't need it
github_username: JTXYH
facebook_username: 100011175577534
twitter_username: JTX520YH
instagram_username: jtx520yh
# linkedin_username: linkedin_username
# medium_username: medium_username


# Theme Settings
themeColor: "#ff0a16"
primaryDark: "#141414"
accentDark: "#ffffff"
lightGray: "#f2f2f2"
texts: "#333333"


# Posts Settings
show_time_bar: true  # 显示/隐藏阅读进度条
show_modal_on_exit: false  # 访问者离开页面时显示/隐藏推荐模式
show_modal_on_finish_post: true  # 访问者到达帖子末尾时显示/隐藏推荐模式
two_columns_layout: true   # 在一列和两列之间  切换帖子的布局


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-125866747-1"
language: "zh_cn"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
authors: 极客小祥
output: true
paginate_path: "/page/:num/"

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# Table of contents
toc:
  max_level: 2
  list_class: table-of-contents

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-toc

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
